name: parchment_delta
description: Simple and expressive format for describing rich-text content created for Quill.js editor. This package is unofficial port to Dart from JavaScript.
version: 1.0.0
homepage: https://github.com/fleather-editor/parchment_delta.git

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  quiver: ^3.0.0
  diff_match_patch: ^0.4.1

dev_dependencies:
  coverage: ^1.0.0
  lints: ^3.0.0
  test: ^1.17.5
