name: quill_delta
description: Simple and expressive format for describing rich-text content created for Quill.js editor. This package is unofficial port to Dart from JavaScript.
version: 2.0.1
homepage: https://github.com/pulyaevskiy/quill-delta-dart
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  quiver: ^2.0.0

dev_dependencies:
  coverage: ^1.0.0
  pedantic: ^1.11.0
  test: ^1.17.5
